In [3]:
import numpy as np

In [4]:
arr=np.array([1,2,3,4,5])
print(arr)
type(arr)
print(arr.shape)
print(len(arr))

[1 2 3 4 5]
(5,)
5


In [5]:
a=np.array([[2,3,3,5,6],[4,5,6,1,2],[5,4,2,3,6]])
print(a)
print(a.shape)
print(len(a))
print(a.size)

[[2 3 3 5 6]
 [4 5 6 1 2]
 [5 4 2 3 6]]
(3, 5)
3
15


to see the dimention of a array wn need array name with .ndim and      itemsize will tell the byte  size of the array

In [6]:
three=np.array([[[1,2,3],[2,3,4]],[[3,4,2],[4,5,1]],[[2,5,1],[7,2,4]]])
print(three.ndim)
print(three.shape)
print(len(three))
print(three.dtype)
print(three.size)
print(three.itemsize)

3
(3, 2, 3)
3
int32
18
4


#numpy is faster than list and this is the proof for it

In [7]:
%timeit cube=[i**3 for i in range(100)]    

23.6 µs ± 454 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [8]:
num=np.arange(100)
%timeit num**3

908 ns ± 40.4 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [9]:
import time
import sys
cube=[i**3 for i in range(100)] 
print('memory alocation in the list =',sys.getsizeof(cube)*len(cube))

memory alocation in the list = 92000


In [10]:
num=np.arange(100)
cube=num+3
print('memory alocation in the list =',num.size+cube.itemsize)

memory alocation in the list = 104


In [11]:
np.empty([2,2])

array([[6.01347002e-154, 6.79218245e+199],
       [3.99528949e+252, 7.47644733e-114]])

In [12]:
c=np.zeros([3,3])
print(c)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [13]:
c=np.ones([3,3])
print(c)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [14]:
f=np.eye(3,3)
print(f)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [15]:
h=np.full((2,2),4)
print(h)

[[4 4]
 [4 4]]


array creation using numerical range

In [16]:
num=np.arange(5)
print(num)

[0 1 2 3 4]


In [24]:
num2=np.arange(10,30,5)
print(num2)

[10 15 20 25]


In [29]:
num3=np.arange(5,dtype='float64')
print(num3)

[0. 1. 2. 3. 4.]


In [31]:
num4=np.arange(10,30,2,dtype='float64')
print(num4)

[10. 12. 14. 16. 18. 20. 22. 24. 26. 28.]


numpy.linspace
syntex
numpy.linspace(start,stop,num,endpoint,retstep,dtype)

In [39]:
g=np.linspace(10,30,5)
print(g)

[10. 15. 20. 25. 30.]


In [46]:
k=np.linspace(10,30,9,retstep=True)
print(k)

(array([10. , 12.5, 15. , 17.5, 20. , 22.5, 25. , 27.5, 30. ]), 2.5)
